// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type User struct {
	ID        int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Email     string
}
